name: Machine Learning Client CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs: 
  build-and-test:
    runs-on: ubuntu-latest

    # # test on two different python versions (if needed)
    # strategy:
    #   matrix:
    #     python-version: [3.11, 3.12]


    steps: 

      # checkout code
      - name: Checkout code
        uses: actions/checkout@v3


      # setup python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      # install pip and upgrade, and pipenv
      - name: Install pip and pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv


      # install dependencies
      - name: Install dependencies with pipenv
        working-directory: ./machine-learning-client
        run: |
          pipenv install --dev 


      # check lint formatting on the web-app
      - name: Lint machine learning client with pylint
        working-directory: ./machine-learning-client
        run: |
          pipenv run pylint ml_client.py


      # format with black
      - name: Format with Black
        working-directory: ./machine-learning-client
        run: |
          pipenv run black . 


      # run the web-app pytests
      - name: Run web-app tests
        working-directory: ./machine-learning-client
        run: |
          pipenv run pytest 